Добавил массивы в сценарий index.php двумерный массив
htmlacademy-php/785843-readme-12 pull request #4
Opened 2020-11-01 13:01 UTC by silverfly555

для показа карточки одного поста.

2020-11-04 13:11 UTC, b1rdex requested changes

2020-11-04 13:11 UTC, b1rdex commented on index-welcome.html
> +<!DOCTYPE html>
Этот файл удаляй

2020-11-04 13:11 UTC, b1rdex commented on .htaccess
> +<IfModule dir_module>
Этот файл думаю можно удалить

2020-11-04 13:11 UTC, b1rdex commented on index-welcome.html
> +<!DOCTYPE html>
И там ещё ~$index.html нужно удалить

2020-11-04 13:11 UTC, b1rdex commented on index.php
> +            ];
Массив нужно переделать. Сейчас у тебя тут, по факту, 6 переменных и 6 массивов получилось. Из них $info_card самый бесполезный.

Нужно использовать ассоциативный массив, а не списки. Т.е. чтобы массив был сразу как таблица, примерно вот так:

```php
$posts = [
	[
		'title' => 'заголовок',
		'type' => 'тип',
		'content' => 'содержимое',
		'user' => 'имя юзера',
		'avatar' => 'аватар',
	],
	[
		'title' => 'заголовок',
		'type' => 'тип',
		'content' => 'содержимое',
		'user' => 'имя юзера',
		'avatar' => 'аватар',
	],
];
```

Так у тебя в $posts на каждую запись будет сразу строка соответствующих данных. Тогда и в цикле с ним будет работать проще:

```php
foreach ($posts as $post) {
	echo $post['title'];
	echo $post['type'];
	// и так далее. Т.е. в $post будет сразу весь пост и каждое поле с заданным ключём
}
```

2020-11-04 13:11 UTC, b1rdex commented on index.php
> +			$ind=0;
При foreach обычно не нужны индексы. Если переделаешь массив, они не понадобятся.

2020-11-04 13:11 UTC, b1rdex commented on index.php
> +        <?php foreach ($info_card as $x1): ?>
Переменным нужно давать осмысленные названия, это есть в критериях защиты: https://up.htmlacademy.ru/php/12/criteries

2020-11-04 13:11 UTC, b1rdex commented on index.php
>              <div class="visually-hidden" id="donor">
Из задания: «После выполнения предыдущих шагов тег div#donor вместе со всем содержимым нужно удалить»

2020-11-04 13:11 UTC, b1rdex commented on index.php
>              <article class="popular__post post">
Foreach должен быть вокруг этого тега, т.е. на каждый пост выводим `<article>` со всем его содержимым

2020-11-08 08:27 UTC, b1rdex requested changes

2020-11-08 08:27 UTC, b1rdex commented on index.php
>                                  <img class="post__author-avatar" src="img/" alt="Аватар пользователя">
Путь к файлу надо выводить в атрибуте src у img

2020-11-08 08:27 UTC, b1rdex commented on index.php
> +                    <?php echo $post['type']; ?>
Это нужно удалить

2020-11-08 08:27 UTC, b1rdex commented on index.php
> +                };
У тебя в условиях стоит `=`, т.е. это не сравнение, а присваивание. Таким образом, все посты выведутся с типом post-link.

2020-11-08 08:27 UTC, b1rdex commented on index.php
> +                    <?php echo $post['content']; ?>
Нужно не просто вывести контент, а по-разному (как было в #donor), в зависимости от типа поста

2020-11-09 05:49 UTC, b1rdex requested changes

2020-11-09 05:49 UTC, b1rdex commented on index.php
> +                        </blockquote>
Для этого типа не нужно выводить как цитату

2020-11-09 08:40 UTC, silverfly555 commented on index.php
> +                        </blockquote>
Убрал <blockquote>

2020-11-09 08:47 UTC, silverfly555 commented on index.php
> +                        </blockquote>
&#60blockquote&#62

2020-11-09 10:43 UTC, merged