Начинаем внедрение функции показа даты
htmlacademy-php/785843-readme-12 pull request #7
Opened 2020-12-07 08:01 UTC by silverfly555

2020-12-14 10:05 UTC, b1rdex requested changes

2020-12-14 10:05 UTC, b1rdex commented on templates/main.php
> +              $index++; ?>
Тут можно было не делать вручную $index, а использовать индекс из foreach

2020-12-14 10:05 UTC, b1rdex commented on index.php
> +{
`strtotime($time)` стоит вынести в переменную, чтобы не дублировать

`strtotime(date("Y-m-d H:i:s"))` нужно заменить на `time()` и тоже вынести в переменную.

2020-12-14 10:05 UTC, b1rdex commented on templates/main.php
> +                                <time class="post__time" datetime="<?php echo $random_date; ?>">дата <?php echo time_print($random_date); ?></time>
Тут ещё нужно добавить атрибут title: `Дату в формате “дд.мм.гггг чч:мм” показывайте внутри атрибута title этого тега.`

2020-12-14 10:05 UTC, b1rdex commented on templates/layout.php
> +    echo date('d.m.y G:i:s'); ?>
Это убрать

2020-12-14 10:05 UTC, b1rdex commented on index.php
> +{
Когда это сделаешь, то заметишь, что у тебя там со скобками ошибка ниже

2020-12-14 10:05 UTC, b1rdex commented on index.php
> +        $result=(strtotime(date("Y-m-d H:i:s")-strtotime($time)))/3600;
Т.к. нужно нам количество минут, то делим на 60 и результат приводим к целому: через `(int)` каст или функцию `ceil()`

2020-12-14 10:05 UTC, b1rdex commented on index.php
> +        return date('i', $result).get_noun_plural_form($result, ' минута', ' минуты', ' минут').' назад';
Тут (и во всех return ниже) нужно оставить только `get_noun_plural_form()`, т.к. вывод дублируется.

2020-12-14 10:05 UTC, b1rdex commented on index.php
> +      elseif (strtotime(date("Y-m-d H:i:s"))-strtotime($time)>3600 && strtotime(date("Y-m-d H:i:s")-strtotime($time)<86400)) {
Все `elseif` замени на просто `if`, т.к. у тебя везде return в теле

2020-12-14 10:05 UTC, b1rdex commented on index.php
> +      elseif (strtotime(date("Y-m-d H:i:s"))-strtotime($time)>3600 && strtotime(date("Y-m-d H:i:s")-strtotime($time)<86400)) {
https://up.htmlacademy.ru/php/12/criteries#d7

2020-12-14 10:05 UTC, b1rdex commented on index.php
> +        $result=(strtotime(date("Y-m-d H:i:s")-strtotime($time)))/86400;
Нам нужны часы, а не сутки. И тоже делаем целое.

2020-12-14 10:05 UTC, b1rdex commented on index.php
> +        $result=(strtotime(date("Y-m-d H:i:s")-strtotime($time)))/604800;
Тут нужны сутки

2020-12-14 10:05 UTC, b1rdex commented on index.php
> +        $result=(strtotime(date("Y-m-d H:i:s")-strtotime($time)))/3024000;
Тут недели

2020-12-14 10:05 UTC, b1rdex commented on index.php
> +        $result=(strtotime(date("Y-m-d H:i:s")-strtotime($time)))/3024000;
А тут верно, месяцы :) тоже целое

2020-12-14 17:26 UTC, silverfly555 commented on index.php
> +        return date('i', $result).get_noun_plural_form($result, ' минута', ' минуты', ' минут').' назад';
> Тут (и во всех return ниже) нужно оставить только `get_noun_plural_form()`, т.к. вывод дублируется.

Я перенес слово "назад" в main.phph, а date('i', $result) во всех return же разные (минуты, часы, дни, ...), как с ними быть?

2020-12-19 11:04 UTC, b1rdex requested changes

2020-12-19 11:04 UTC, b1rdex commented on index.php
> +  $un_time=time();
Давай осмысленные имена переменным, про это есть критерий
st_time = просто time
un_time = now

2020-12-19 11:04 UTC, b1rdex commented on index.php
> +        return date('i', $result).get_noun_plural_form($result, ' минута', ' минуты', ' минут');
Вызов date() тут и ниже – это ошибка. В $result у тебя количество минут/часов и т.д., date такие аргументы не принимает.

Меняй на просто `$result . ' ' . get_noun_plural_form()` (пробел лучше вынести как я написал, а не писать его в каждое слово).

Это всё тут и ниже нужно сделать

2020-12-19 11:04 UTC, b1rdex commented on index.php
> +        return date('h', $result).get_noun_plural_form($result, ' час', ' часов', ' часа');
тут часа и часов перепутано

2020-12-19 11:04 UTC, b1rdex commented on index.php
> +        $result=floor(($un_time-$st_time))/3024000;
тут скобки перепутаны, нужно округлять после деления

2020-12-20 14:43 UTC, b1rdex approved these changes

2020-12-20 14:43 UTC, b1rdex commented on index.php
> +      if ($now-$time>=3024000) {
На заметку: тут можно убрать if и оставить только тело, т.к. условие всегда будет выполняться. Время меньше 5 недель уже учтено выше в условиях.

2020-12-20 14:43 UTC, merged